// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zufqthfoenayzbmgnact.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1ZnF0aGZvZW5heXpibWduYWN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODc1NTIsImV4cCI6MjA1ODk2MzU1Mn0.qadDmnsTu1632Z0C7_dfvgLRWgbT-_4KSro3NV2ghlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);